# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: param1
    type: string
  - name: param2
    type: string
  - name: DependsOn
    type: string
    default: ""

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# https://learn.microsoft.com/zh-cn/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#selectively-exclude-a-stage
  # parameters:
  #   - name: runPerfTests
  #     type: boolean
  #     default: false
    
  #   trigger: none
    
  #   stages:
  #   - stage: Build
  #     displayName: Build
  #     jobs:
  #     - job: Build
  #       steps:
  #       - script: echo running Build
    
    
  #   - stage: UnitTest
  #     displayName: Unit Test
  #     dependsOn: Build
  #     jobs:
  #     - job: UnitTest
  #       steps:
  #       - script: echo running UnitTest
    
    
  #   - ${{ if eq(parameters.runPerfTests, true) }}:
  #     - stage: PerfTest
  #       displayName: Performance Test
  #       dependsOn: Build
  #       jobs:
  #       - job: PerfTest
  #         steps:
  #         - script: echo running PerfTest
    
    
  #   - stage: Deploy
  #     displayName: Deploy
  #     dependsOn: UnitTest
  #     jobs:
  #     - job: Deploy
  #       steps:
  #       - script: echo running UnitTest