name: Run get pr changefiles by ps script

on:
  pull_request:
    branches:
      - main 
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest
    env:
      SCRIPT_DIR: ./eng/scripts/ValidateYaml
      TEMP_PATH: ./temp-output.txt

    steps:
      - name: Run PowerShell script
        run: |
          Write-Output "Running PowerShell!"
          $PSVersionTable
        shell: pwsh

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get pr changefiles
        shell: pwsh
        run: |
          Write-Output "Reading from the temporary file! ${{ env.SYSTEM_PULLREQUEST_SOURCECOMMITID }}"
          powershell ./eng/common/scripts/get-changedfiles.ps1
        env:
          SYSTEM_PULLREQUEST_SOURCECOMMITID: ${{ github.event.pull_request.head.sha }}
          SYSTEM_PULLREQUEST_TARGETBRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_EVENT_PULL_REQUEST_BASE_REPO_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
          GITHUB_EVENT_PULL_REQUEST_BASE_REPO_NAME: ${{ github.event.pull_request.base.repo.name }}
          GITHUB_EVENT_PULL_REQUEST_BASE_REF: ${{ github.event.pull_request.base.ref }}
          GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_NAME: ${{ github.event.pull_request.head.repo.name }}
          GITHUB_EVENT_PULL_REQUEST_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
