name: sync-common-types-files
on:
  push:
    branches:
      - main
    paths: 
      - 'specification/common-types/**'
  schedule:
    - cron: '* 8 * * 1' 
    # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#schedule
    # https://crontab.guru/
  workflow_dispatch:
jobs:
  sync-common-types-files:
    name: sync-common-types-files
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Repo File Sync Action
          uses: BetaHuhn/repo-file-sync-action@v1
          # https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-action-inputs
          with:
            GH_PAT: ${{secrets.GH_PAT}}
            CONFIG_PATH: .github/sync.yml
            GIT_EMAIL: 347142915@qq.com
            GIT_USERNAME: JackTn
            ASSIGNEES: |
              JackTn
            PR_LABELS: false