name: sync-common-types-files

on:
  push:
    branches:
      - main
    paths: 
      - 'specification/common-types/**'
  schedule:
    - cron: '* */3 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点

jobs:
  syncS:
    name: syncA
    runs-on: ubuntu-latest
    steps:
        - name: test echo
          run: echo ${{  secrets.GH_PAT  }}
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Repo File Sync Action
          id: sync
          uses: BetaHuhn/repo-file-sync-action@v1
          with:
            ACTIONS_STEP_DEBUG : true
            GH_PAT: ${{secrets.GH_PAT}}
            CONFIG_PATH: ${{env.sync-common-types-files.CONFIG_PATH}}
            GIT_EMAIL: ${{env.sync-common-types-files.GIT_EMAIL}}
            GIT_USERNAME: ${{env.sync-common-types-files.GIT_USERNAME}}
            ASSIGNEES: ${{env.sync-common-types-files.ASSIGNEES}}
            COMMIT_PREFIX: ${{env.sync-common-types-files.COMMIT_PREFIX}}
            COMMIT_BODY: ${{env.sync-common-types-files.COMMIT_BODY}}
            PR_BODY: ${{env.sync-common-types-files.PR_BODY}}
            BRANCH_PREFIX: ${{env.sync-common-types-files.BRANCH_PREFIX}}
        - run: echo "new pr is in the ${{ steps.sync.outputs.pull_request_urls }}"
