name: sync-common-types-files

on:
  push:
    branches:
      - main
    paths: 
      - 'specification/common-types/**'
  schedule:
    - cron: '* */3 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
  workflow_dispatch:

jobs:
  sync-common-types-files:
    name: sync-common-types-files
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Repo File Sync Action
          id: sync
          uses: BetaHuhn/repo-file-sync-action@v1
          with:
            ACTIONS_STEP_DEBUG : false
            PR_LABELS: false
            GH_PAT: ${{secrets.GH_PAT}}
            CONFIG_PATH: .github/sync.yml
            GIT_EMAIL: 347142915@qq.com
            GIT_USERNAME: JackTn
            ASSIGNEES: |
              JackTn
