 name: GitHub Actions Demo 2
 on: 
   push:
     branches:
       - main
     paths: 
       - 'specification/common-types/**'
 jobs:
   Explore-GitHub-Actions34:
     name: sync-common-types-files-1
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: sync-common-types-files-local
         uses: ./
         with:
            OWNER: JackTn
            REPO: script_github_actions-pr
            BRANCH: main
            FILE_PATH: specification/common-types
